config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resource :session, only: [:new, :create, :destroy]
  resources :users do
    post 'ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  resources :places, only: [:index, :show]
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  root "breweries#index"
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage
  has_secure_password

  has_many :memberships, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true, length: { minimum: 3, maximum: 30 }
  validates :password, presence: true, format: { with: /\A(?=.*[a-zA-Z])(?=.*[A-Z])(?=.*[0-9]).{4,}\z/ }

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?

    ratings.group_by{ |r| r.beer.style }.map{ |style, ratings| next ratings.sum(&:score), style }.max_by{ |score, _style| score }[1]
  end

  def favorite_brewery
    return nil if ratings.empty?

    ratings.group_by{ |r| r.beer.brewery }.map{ |brewery, ratings| next ratings.sum(&:score), brewery }.max_by{ |score, _brewery| score }[1]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :ensure_that_admin, only: [:ban]

  def ban
    user = User.find(params[:id])
    user.update_attribute :banned, !user.banned
    new_status = user.banned? ? "banned" : "not banned"
    redirect_to user, notice: "User is now #{new_status}"
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    respond_to do |format|
      if @user == current_user
        @user.destroy
        session[:user_id] = nil
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      else
        format.html { redirect_to users_url, notice: "User was unsccessfully destroyed." }
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div>
      <%= form.label :username, style: "display: block" %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div>
    <%= form.label :password, style: "display: block"%>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block"%>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <% if user.banned  %>
    <span class="badge bg-secondary">banned</span>
  <% end %>
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>
</div>

app/views/users/edit.html.erb
<% if @user.new_record? %>
  <h1>Editing user</h1>
<% else %>
  <h1>Change password for user <%= @user.username %></h1>
<% end %>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h3>
  <strong>Username: </strong><%= @user.username %>
</h3>

<% if @user.ratings.empty? %>
  User has no ratings.
<% else %>
  Has made <%= pluralize @user.ratings.count, 'rating' %>, average rating <%= round(@user.average_rating) %>
  <strong>ratings</strong>
  <ul>
    <% @user.ratings.each do |rating| %>
      <li> <%= render rating %> <%= link_to 'delete', rating, data: {"turbo-method": :delete} %> </li>
    <% end %>
  </ul>
  <p>Favorite style is <%= @user.favorite_style.name %></p>
    <br />
  <p>Favorite brewery is <%= @user.favorite_brewery.name %></p>
<% end %>

<% if @user == current_user && @user.beer_clubs.empty? %>
  <br>
  <%= link_to "Join a club!", new_membership_path, class: "btn btn-primary" %>
<% else %>
  <h3><strong>Clubs:</strong></h3>
  <ul>
    <% @user.beer_clubs.each do |club| %>
      <li> <%= link_to club.name, club %> </li>
    <% end %>
  </ul>
<% end %>

<% if current_user && current_user.admin %>
  <div>
    <%= link_to "Toggle user ban", ban_user_path(@user.id), data: {turbo_method: "post"}, class: "btn btn-danger" %>
  </div>
<% end %>

<% if @user == current_user %>
<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete, class: "btn btn-danger" %>
</div>
<% end %>