config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resource :session, only: [:new, :create, :destroy]
  resources :users do
    post 'ban', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  resources :places, only: [:index, :show]
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  root "breweries#index"
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: { only_integer: true,
                                   greater_than: 1039,
                                   less_than_or_equal_to: ->(_) { Time.now.year } }

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  include RatingAverage
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_admin, only: [:destroy]

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active
    new_status = brewery.active? ? "active" : "retired"
    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  # GET /breweries or /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all
  end

  def list
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <h2>
    <%= brewery.name %>
    <% if not brewery.active  %>
      <span class="badge bg-secondary">retired</span>
    <% end %>
  </h2>

  <p>
    <i>
      Established at <%= brewery.year %>
    </i>
  </p>

  <p>
    Beers count: <%= brewery.beers.count %>
  </p>

  <p>
    <% brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %>
    <% end %>
  </p>

<% if brewery.ratings.empty? %>
  Brewery has not yet been rated!
<% else %>
  Brewery has <%= pluralize brewery.ratings.count, 'rating' %> with an average of <%= round(brewery.average_rating) %>
<% end %>

</div>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<div id="breweries">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Year</th>
      </tr>
    </thead>
    <% @active_breweries.each do |brewery| %>
      <tbody>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tbody>
    <% end %>
  </table>
</div>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<div id="retired_breweries">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Year</th>
      </tr>
    </thead>
    <% @retired_breweries.each do |brewery| %>
      <tbody>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tbody>
    <% end %>
  </table>
</div>


<%= link_to('List of beers', beers_path, class:'btn btn-primary') %>
<%= link_to('New brewery', new_brewery_path, class:'btn btn-primary') if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <thead>
    <tr>
      <th> <span id="name">Name</span> </th>
      <th> <span id="year">Year</span> </th>
      <th> <span id="beers">Beers</span> </th>
      <th> <span id="active">Active</span> </th>
    </tr>
  <thead>
  <tbody>
    <div id="brewerylist"></div>
  </tbody>
</table>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<%= render @brewery %>
<br>
<div>
  <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-secondary" %>
  <%= link_to('Edit this brewery', edit_brewery_path(@brewery), class: "btn btn-primary") if current_user %>
  <%= link_to "Back to breweries", breweries_path, class: "btn btn-primary" %>
</div>
<br>
<%= button_to('Destroy this brewery', @brewery, method: :delete, class: "btn btn-danger") if current_user %>